version: '3'

services:
  web-app-service:
    build: ./frontend
    volumes: 
      - ./frontend:/usr/src/app
    ports:
      - 3000
  
  backend-ml-service:
    build: ./backend
    volumes:
    - ./backend:/usr/src/app
    ports:
    - 4000
  
  database:
    image: mysql:8.0.21
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    
